// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/python_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PythonService_SearchEnvironments_FullMethodName = "/pythonmanager.PythonService/SearchEnvironments"
	PythonService_ExecutePython_FullMethodName      = "/pythonmanager.PythonService/ExecutePython"
)

// PythonServiceClient is the client API for PythonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for Python management
type PythonServiceClient interface {
	SearchEnvironments(ctx context.Context, in *SearchEnvironmentsRequest, opts ...grpc.CallOption) (*SearchEnvironmentsResponse, error)
	ExecutePython(ctx context.Context, in *ExecutePythonRequest, opts ...grpc.CallOption) (*ExecutePythonResponse, error)
}

type pythonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPythonServiceClient(cc grpc.ClientConnInterface) PythonServiceClient {
	return &pythonServiceClient{cc}
}

func (c *pythonServiceClient) SearchEnvironments(ctx context.Context, in *SearchEnvironmentsRequest, opts ...grpc.CallOption) (*SearchEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEnvironmentsResponse)
	err := c.cc.Invoke(ctx, PythonService_SearchEnvironments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonServiceClient) ExecutePython(ctx context.Context, in *ExecutePythonRequest, opts ...grpc.CallOption) (*ExecutePythonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePythonResponse)
	err := c.cc.Invoke(ctx, PythonService_ExecutePython_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PythonServiceServer is the server API for PythonService service.
// All implementations must embed UnimplementedPythonServiceServer
// for forward compatibility.
//
// Service definition for Python management
type PythonServiceServer interface {
	SearchEnvironments(context.Context, *SearchEnvironmentsRequest) (*SearchEnvironmentsResponse, error)
	ExecutePython(context.Context, *ExecutePythonRequest) (*ExecutePythonResponse, error)
	mustEmbedUnimplementedPythonServiceServer()
}

// UnimplementedPythonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPythonServiceServer struct{}

func (UnimplementedPythonServiceServer) SearchEnvironments(context.Context, *SearchEnvironmentsRequest) (*SearchEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEnvironments not implemented")
}
func (UnimplementedPythonServiceServer) ExecutePython(context.Context, *ExecutePythonRequest) (*ExecutePythonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePython not implemented")
}
func (UnimplementedPythonServiceServer) mustEmbedUnimplementedPythonServiceServer() {}
func (UnimplementedPythonServiceServer) testEmbeddedByValue()                       {}

// UnsafePythonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PythonServiceServer will
// result in compilation errors.
type UnsafePythonServiceServer interface {
	mustEmbedUnimplementedPythonServiceServer()
}

func RegisterPythonServiceServer(s grpc.ServiceRegistrar, srv PythonServiceServer) {
	// If the following call panics, it indicates UnimplementedPythonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PythonService_ServiceDesc, srv)
}

func _PythonService_SearchEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonServiceServer).SearchEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonService_SearchEnvironments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonServiceServer).SearchEnvironments(ctx, req.(*SearchEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonService_ExecutePython_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePythonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonServiceServer).ExecutePython(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonService_ExecutePython_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonServiceServer).ExecutePython(ctx, req.(*ExecutePythonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PythonService_ServiceDesc is the grpc.ServiceDesc for PythonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PythonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pythonmanager.PythonService",
	HandlerType: (*PythonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchEnvironments",
			Handler:    _PythonService_SearchEnvironments_Handler,
		},
		{
			MethodName: "ExecutePython",
			Handler:    _PythonService_ExecutePython_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/python_service.proto",
}
