// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/python_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PythonEnvironment represents a Python environment
type PythonEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Encoding      string                 `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"` // wsl or windows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythonEnvironment) Reset() {
	*x = PythonEnvironment{}
	mi := &file_proto_python_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythonEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonEnvironment) ProtoMessage() {}

func (x *PythonEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_python_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonEnvironment.ProtoReflect.Descriptor instead.
func (*PythonEnvironment) Descriptor() ([]byte, []int) {
	return file_proto_python_service_proto_rawDescGZIP(), []int{0}
}

func (x *PythonEnvironment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PythonEnvironment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PythonEnvironment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PythonEnvironment) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PythonEnvironment) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *PythonEnvironment) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// Request to search for Python environments
type SearchEnvironmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEnvironmentsRequest) Reset() {
	*x = SearchEnvironmentsRequest{}
	mi := &file_proto_python_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEnvironmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEnvironmentsRequest) ProtoMessage() {}

func (x *SearchEnvironmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_python_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEnvironmentsRequest.ProtoReflect.Descriptor instead.
func (*SearchEnvironmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_python_service_proto_rawDescGZIP(), []int{1}
}

// Response containing Python environments
type SearchEnvironmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environments  []*PythonEnvironment   `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEnvironmentsResponse) Reset() {
	*x = SearchEnvironmentsResponse{}
	mi := &file_proto_python_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEnvironmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEnvironmentsResponse) ProtoMessage() {}

func (x *SearchEnvironmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_python_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEnvironmentsResponse.ProtoReflect.Descriptor instead.
func (*SearchEnvironmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_python_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchEnvironmentsResponse) GetEnvironments() []*PythonEnvironment {
	if x != nil {
		return x.Environments
	}
	return nil
}

// Request to execute a Python script
type ExecutePythonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PythonPath    string                 `protobuf:"bytes,1,opt,name=python_path,json=pythonPath,proto3" json:"python_path,omitempty"`
	Arguments     []string               `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	CaptureOutput bool                   `protobuf:"varint,3,opt,name=capture_output,json=captureOutput,proto3" json:"capture_output,omitempty"`
	AutoExit      bool                   `protobuf:"varint,4,opt,name=auto_exit,json=autoExit,proto3" json:"auto_exit,omitempty"`
	Interactive   bool                   `protobuf:"varint,5,opt,name=interactive,proto3" json:"interactive,omitempty"`             // Whether the script requires interactive input
	InputData     string                 `protobuf:"bytes,6,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"` // Input data to provide to the script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePythonRequest) Reset() {
	*x = ExecutePythonRequest{}
	mi := &file_proto_python_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePythonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePythonRequest) ProtoMessage() {}

func (x *ExecutePythonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_python_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePythonRequest.ProtoReflect.Descriptor instead.
func (*ExecutePythonRequest) Descriptor() ([]byte, []int) {
	return file_proto_python_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutePythonRequest) GetPythonPath() string {
	if x != nil {
		return x.PythonPath
	}
	return ""
}

func (x *ExecutePythonRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecutePythonRequest) GetCaptureOutput() bool {
	if x != nil {
		return x.CaptureOutput
	}
	return false
}

func (x *ExecutePythonRequest) GetAutoExit() bool {
	if x != nil {
		return x.AutoExit
	}
	return false
}

func (x *ExecutePythonRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ExecutePythonRequest) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

// Response from executing a Python script
type ExecutePythonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePythonResponse) Reset() {
	*x = ExecutePythonResponse{}
	mi := &file_proto_python_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePythonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePythonResponse) ProtoMessage() {}

func (x *ExecutePythonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_python_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePythonResponse.ProtoReflect.Descriptor instead.
func (*ExecutePythonResponse) Descriptor() ([]byte, []int) {
	return file_proto_python_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutePythonResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutePythonResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecutePythonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_python_service_proto protoreflect.FileDescriptor

const file_proto_python_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/python_service.proto\x12\rpythonmanager\"\xa7\x01\n" +
	"\x11PythonEnvironment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\"\x1b\n" +
	"\x19SearchEnvironmentsRequest\"b\n" +
	"\x1aSearchEnvironmentsResponse\x12D\n" +
	"\fenvironments\x18\x01 \x03(\v2 .pythonmanager.PythonEnvironmentR\fenvironments\"\xda\x01\n" +
	"\x14ExecutePythonRequest\x12\x1f\n" +
	"\vpython_path\x18\x01 \x01(\tR\n" +
	"pythonPath\x12\x1c\n" +
	"\targuments\x18\x02 \x03(\tR\targuments\x12%\n" +
	"\x0ecapture_output\x18\x03 \x01(\bR\rcaptureOutput\x12\x1b\n" +
	"\tauto_exit\x18\x04 \x01(\bR\bautoExit\x12 \n" +
	"\vinteractive\x18\x05 \x01(\bR\vinteractive\x12\x1d\n" +
	"\n" +
	"input_data\x18\x06 \x01(\tR\tinputData\"b\n" +
	"\x15ExecutePythonResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xd6\x01\n" +
	"\rPythonService\x12i\n" +
	"\x12SearchEnvironments\x12(.pythonmanager.SearchEnvironmentsRequest\x1a).pythonmanager.SearchEnvironmentsResponse\x12Z\n" +
	"\rExecutePython\x12#.pythonmanager.ExecutePythonRequest\x1a$.pythonmanager.ExecutePythonResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_python_service_proto_rawDescOnce sync.Once
	file_proto_python_service_proto_rawDescData []byte
)

func file_proto_python_service_proto_rawDescGZIP() []byte {
	file_proto_python_service_proto_rawDescOnce.Do(func() {
		file_proto_python_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_python_service_proto_rawDesc), len(file_proto_python_service_proto_rawDesc)))
	})
	return file_proto_python_service_proto_rawDescData
}

var file_proto_python_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_python_service_proto_goTypes = []any{
	(*PythonEnvironment)(nil),          // 0: pythonmanager.PythonEnvironment
	(*SearchEnvironmentsRequest)(nil),  // 1: pythonmanager.SearchEnvironmentsRequest
	(*SearchEnvironmentsResponse)(nil), // 2: pythonmanager.SearchEnvironmentsResponse
	(*ExecutePythonRequest)(nil),       // 3: pythonmanager.ExecutePythonRequest
	(*ExecutePythonResponse)(nil),      // 4: pythonmanager.ExecutePythonResponse
}
var file_proto_python_service_proto_depIdxs = []int32{
	0, // 0: pythonmanager.SearchEnvironmentsResponse.environments:type_name -> pythonmanager.PythonEnvironment
	1, // 1: pythonmanager.PythonService.SearchEnvironments:input_type -> pythonmanager.SearchEnvironmentsRequest
	3, // 2: pythonmanager.PythonService.ExecutePython:input_type -> pythonmanager.ExecutePythonRequest
	2, // 3: pythonmanager.PythonService.SearchEnvironments:output_type -> pythonmanager.SearchEnvironmentsResponse
	4, // 4: pythonmanager.PythonService.ExecutePython:output_type -> pythonmanager.ExecutePythonResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_python_service_proto_init() }
func file_proto_python_service_proto_init() {
	if File_proto_python_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_python_service_proto_rawDesc), len(file_proto_python_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_python_service_proto_goTypes,
		DependencyIndexes: file_proto_python_service_proto_depIdxs,
		MessageInfos:      file_proto_python_service_proto_msgTypes,
	}.Build()
	File_proto_python_service_proto = out.File
	file_proto_python_service_proto_goTypes = nil
	file_proto_python_service_proto_depIdxs = nil
}
